version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: gin-rest-api-psql
    environment:
      POSTGRES_DB: gin-rest-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
